export interface AiTool {
  id: number;
  slug: string;
  name: string;
  maker: string;
  website: string;
  tagline: string;
  category: string;
  specialty: string;
  howItWorks: string;
  captainsReview: string;
  rating: number; // 1-5
  tags: string[];
}

export const AI_TOOLS: AiTool[] = [
  {
    id: 1,
    slug: "chatgpt",
    name: "ChatGPT",
    maker: "OpenAI",
    website: "https://chat.openai.com",
    tagline: "The world's most capable conversational AI",
    category: "Language Model",
    specialty: "Writing, coding, strategy, research, analysis",
    howItWorks: "ChatGPT is built on GPT-4o, a large language model trained on vast amounts of internet text and fine-tuned with human feedback (RLHF). It predicts the most contextually appropriate next token in a sequence, enabling fluid conversation, code generation, reasoning chains, and multimodal understanding of images and voice.",
    captainsReview: "This is your primary co-pilot — the Swiss Army knife of AI. For aviation professionals, ChatGPT excels at drafting technical documentation, parsing regulation text, building checklists, and thinking through complex operational scenarios. The voice mode is particularly useful when your hands are occupied. Mandatory on every flight plan.",
    rating: 5,
    tags: ["Text", "Code", "Voice", "Vision"],
  },
  {
    id: 2,
    slug: "claude",
    name: "Claude",
    maker: "Anthropic",
    website: "https://claude.ai",
    tagline: "Reasoning and long-context analysis at scale",
    category: "Language Model",
    specialty: "Long documents, complex reasoning, nuanced analysis",
    howItWorks: "Claude is trained using Constitutional AI — a self-critique and revision process that bakes safety and helpfulness into the model's core values. Its 200K token context window lets it ingest entire flight manuals, maintenance logs, or regulatory documents in a single conversation and reason across them coherently.",
    captainsReview: "When you need to analyze a 300-page maintenance manual or cross-reference multiple FAA advisory circulars simultaneously, Claude is the instrument you reach for. Its refusal to hallucinate under pressure and its methodical reasoning style make it the most trustworthy co-pilot for high-stakes document work. Think of it as your senior first officer — calm, precise, thorough.",
    rating: 5,
    tags: ["Text", "Analysis", "Long Context"],
  },
  {
    id: 3,
    slug: "gemini",
    name: "Gemini",
    maker: "Google DeepMind",
    website: "https://gemini.google.com",
    tagline: "Google's native multimodal intelligence engine",
    category: "Language Model",
    specialty: "Multimodal tasks, real-time data, Google Workspace integration",
    howItWorks: "Gemini Ultra is Google's most capable model, built natively multimodal — it understands text, images, audio, video, and code in parallel rather than converting between modalities. Deep integration with Google Search gives it access to real-time information, and its Workspace plugins allow it to act directly on Gmail, Docs, Sheets, and Drive.",
    captainsReview: "Gemini's real power is ecosystem integration. If your operations team runs on Google Workspace, having an AI that can read your Sheets fuel logs, summarize your Drive briefings, and pull live weather NOTAMs simultaneously is genuinely mission-critical. Strong on multimodal analysis — upload cockpit camera footage or MRO images and get intelligent assessment.",
    rating: 4,
    tags: ["Multimodal", "Real-time", "Google Suite"],
  },
  {
    id: 4,
    slug: "copilot",
    name: "Microsoft Copilot",
    maker: "Microsoft",
    website: "https://copilot.microsoft.com",
    tagline: "AI-powered productivity across the Microsoft ecosystem",
    category: "Productivity AI",
    specialty: "Microsoft 365 integration, document creation, enterprise workflows",
    howItWorks: "Copilot is powered by GPT-4 and deeply integrated into the Microsoft 365 suite. It uses Microsoft Graph to understand your organization's context — your emails, meetings, documents, and calendar — applying AI directly to your workflow inside Word, Excel, PowerPoint, Teams, and Outlook without switching context.",
    captainsReview: "For enterprise aviation operators running on Microsoft infrastructure, Copilot is a genuine force multiplier. Automatically drafting incident reports from Teams meeting transcripts, generating maintenance summaries from Excel data, or building PowerPoint briefings from raw performance data — it handles the administrative cockpit load so your team stays focused on flight ops.",
    rating: 4,
    tags: ["Productivity", "Microsoft 365", "Enterprise"],
  },
  {
    id: 5,
    slug: "perplexity",
    name: "Perplexity",
    maker: "Perplexity AI",
    website: "https://perplexity.ai",
    tagline: "AI-native research engine with live citations",
    category: "Research AI",
    specialty: "Real-time web research, cited answers, technical deep dives",
    howItWorks: "Perplexity combines a large language model with a real-time web search engine, crawling authoritative sources and synthesizing answers with inline citations. Unlike standard search, it understands nuanced questions, synthesizes across multiple sources, and presents the answer in plain language rather than a list of links to sort through.",
    captainsReview: "Best-in-class for technical research missions. When you need current EASA regulations, the latest NTSB accident reports, or competitive intelligence on fleet management software — Perplexity lands the answer in seconds with full source transparency. The cited format is critical in aviation where you need to know exactly where information comes from. Cleared for all research operations.",
    rating: 5,
    tags: ["Research", "Real-time", "Citations"],
  },
  {
    id: 6,
    slug: "grok",
    name: "Grok",
    maker: "xAI",
    website: "https://grok.x.ai",
    tagline: "Real-time intelligence from the pulse of the internet",
    category: "Language Model",
    specialty: "Real-time X/internet data, current events, technical analysis",
    howItWorks: "Grok is trained by Elon Musk's xAI and has unique real-time access to X (formerly Twitter) data streams, giving it insight into breaking events, live market shifts, and public discourse as it happens. Built with a maximally honest and direct personality, it's less filtered than competitors and designed for deep technical reasoning.",
    captainsReview: "Grok's edge is raw speed on current events. For aviation — tracking live incident reports, monitoring aerospace industry news, or following real-time airspace disruption — its access to X data gives it a 30-minute lead over models without live feeds. The direct personality suits aviation professionals who prefer straight answers over diplomatic hedging. Good for situational awareness.",
    rating: 4,
    tags: ["Real-time", "Social Data", "Current Events"],
  },
  {
    id: 7,
    slug: "midjourney",
    name: "Midjourney",
    maker: "Midjourney Inc.",
    website: "https://midjourney.com",
    tagline: "Cinematic AI imagery at the highest creative altitude",
    category: "Image Generation",
    specialty: "Photorealistic and artistic image generation, concept visualization",
    howItWorks: "Midjourney uses a proprietary diffusion model trained on a curated dataset of high-quality images. It interprets natural language prompts and generates visuals through an iterative denoising process, producing imagery renowned for its cinematic quality, lighting precision, and artistic coherence across styles from photorealism to concept art.",
    captainsReview: "For aviation marketing, fleet presentations, training material visualization, and conceptual aircraft design, Midjourney is in a class of its own. The image quality is simply unmatched — generating photorealistic cockpit views, atmospheric fleet photography, or sleek infographic assets that would take a design team days. If your brand needs visual altitude, this is the instrument.",
    rating: 5,
    tags: ["Images", "Creative", "Marketing"],
  },
  {
    id: 8,
    slug: "dalle3",
    name: "DALL-E 3",
    maker: "OpenAI",
    website: "https://openai.com/dall-e-3",
    tagline: "Precision text-to-image generation with high prompt fidelity",
    category: "Image Generation",
    specialty: "Accurate text-following in images, technical diagram creation",
    howItWorks: "DALL-E 3 is a diffusion-based image model trained to follow complex text prompts with exceptional fidelity. Unlike earlier models, it can render legible text within images, maintain compositional accuracy across multiple subjects, and integrates directly into ChatGPT for conversational image iteration — letting you refine outputs through natural dialogue.",
    captainsReview: "DALL-E 3's strength is precision — when you need an image to match your exact specifications, it follows instructions more reliably than Midjourney. Particularly useful for generating diagrams, labeled technical schematics, and infographics where text accuracy matters. Natively integrated into ChatGPT, so it slots into an existing workflow without friction.",
    rating: 4,
    tags: ["Images", "Text-in-Image", "ChatGPT"],
  },
  {
    id: 9,
    slug: "runway",
    name: "Runway Gen-3",
    maker: "Runway",
    website: "https://runwayml.com",
    tagline: "Professional-grade AI video generation and editing",
    category: "Video Generation",
    specialty: "Text-to-video, video-to-video, motion effects, visual VFX",
    howItWorks: "Runway Gen-3 Alpha is a multimodal video foundation model trained on licensed video data. It generates temporally consistent video clips from text or image inputs, understanding camera motion, scene composition, and subject motion. The platform also offers video editing tools including inpainting, background removal, and motion tracking powered by AI.",
    captainsReview: "For aviation marketing teams producing content at scale, Runway transforms the production equation. Generating cinematic aerial footage, flight simulations, and atmospheric brand content without a film crew is a genuine operational advantage. The quality now approaches broadcast standards for shorter formats. Recommended for all digital marketing missions requiring video assets.",
    rating: 4,
    tags: ["Video", "Creative", "Marketing"],
  },
  {
    id: 10,
    slug: "elevenlabs",
    name: "ElevenLabs",
    maker: "ElevenLabs",
    website: "https://elevenlabs.io",
    tagline: "The most realistic AI voice synthesis platform",
    category: "Voice AI",
    specialty: "Voice cloning, text-to-speech, multilingual narration",
    howItWorks: "ElevenLabs trains neural text-to-speech models on voice recordings, capturing the full spectral characteristics of a speaker's voice — intonation, timbre, pacing, and emotional range. Its models can clone a voice from a short sample, generate speech in 29+ languages with native accents, and produce output indistinguishable from human speech in blind tests.",
    captainsReview: "For aviation training programs, safety briefings, IFR tutorial content, and multilingual passenger communications — ElevenLabs is the gold standard. Voice-clone your senior instructors so their expertise scales across 10,000 learners simultaneously. The quality is remarkable and the multilingual capability is essential for international operations. Cleared for all audio production missions.",
    rating: 5,
    tags: ["Voice", "Audio", "Training"],
  },
  {
    id: 11,
    slug: "sora",
    name: "Sora",
    maker: "OpenAI",
    website: "https://sora.com",
    tagline: "Long-form, physics-accurate AI video generation",
    category: "Video Generation",
    specialty: "Long-form video generation, cinematic consistency, physical accuracy",
    howItWorks: "Sora is a diffusion transformer model that understands the physical world — it generates videos up to a minute long with temporal consistency, accurate physics simulation, and complex multi-scene compositions. Trained on diverse video data, it can simulate realistic camera movements, lighting changes, and object interactions that maintain coherence across extended sequences.",
    captainsReview: "Sora represents a generational leap in video generation capability. For aviation applications — simulating emergencies for training, generating realistic weather scenarios, creating procedural training content — its physical accuracy makes it viable for serious simulation work. Access is currently limited but the capability trajectory is clear: this becomes essential infrastructure for training programs within 24 months.",
    rating: 4,
    tags: ["Video", "Simulation", "Training"],
  },
  {
    id: 12,
    slug: "stable-diffusion",
    name: "Stable Diffusion",
    maker: "Stability AI",
    website: "https://stability.ai",
    tagline: "Open-source image AI with unlimited customization",
    category: "Image Generation",
    specialty: "Open-source, fine-tunable, locally deployable image generation",
    howItWorks: "Stable Diffusion is an open-source latent diffusion model that operates in a compressed latent space for efficiency. Because weights are publicly available, organizations can fine-tune models on proprietary imagery — training a custom model on your fleet, facilities, or brand assets — and run it entirely on-premise with zero data leaving the organization.",
    captainsReview: "The critical advantage over commercial alternatives: data sovereignty. For defense contractors and operators handling classified or sensitive visual assets, running Stable Diffusion on-premise means your imagery never touches external servers. The fine-tuning capability is powerful — train it on your actual aircraft and facilities for asset-accurate output. High technical overhead, high security payoff.",
    rating: 4,
    tags: ["Open Source", "On-Premise", "Custom Training"],
  },
  {
    id: 13,
    slug: "github-copilot",
    name: "GitHub Copilot",
    maker: "GitHub / Microsoft",
    website: "https://github.com/features/copilot",
    tagline: "AI pair programmer trained on the world's code",
    category: "Developer AI",
    specialty: "Code completion, generation, review, and debugging",
    howItWorks: "GitHub Copilot uses OpenAI Codex and GPT-4 fine-tuned on billions of lines of public code from GitHub repositories. It integrates directly into IDEs like VS Code as an inline autocomplete and chat interface, suggesting entire functions, writing tests, explaining code, and identifying bugs as developers write — effectively adding an experienced pair programmer to every coding session.",
    captainsReview: "For aviation software teams building flight management systems, ACARS interfaces, or EFB applications — Copilot multiplies engineering output significantly. Internal testing shows 30-55% reduction in time-to-feature for experienced developers. The aviation domain knowledge embedded from open-source avionics projects is a genuine differentiator. Standard issue equipment for any development team.",
    rating: 5,
    tags: ["Code", "Developer", "IDE"],
  },
  {
    id: 14,
    slug: "cursor",
    name: "Cursor",
    maker: "Anysphere",
    website: "https://cursor.sh",
    tagline: "The AI-first code editor that builds with you",
    category: "Developer AI",
    specialty: "Full codebase understanding, multi-file edits, AI code generation",
    howItWorks: "Cursor is a VS Code fork rebuilt around AI-first workflows. It indexes your entire codebase into a vector database, allowing its AI (backed by Claude or GPT-4) to understand project-wide context — not just the current file. This enables it to make coherent changes across multiple files simultaneously, refactor entire modules, and answer questions about system architecture.",
    captainsReview: "Cursor's codebase-wide awareness is the differentiator over Copilot. When working on complex avionics software where a change in one module cascades across the system, having an AI that understands the full call graph is genuinely transformative. The Composer feature — which executes multi-step coding tasks autonomously — reduces implementation time on complex features by 60-70% for senior engineers.",
    rating: 5,
    tags: ["Code", "Developer", "Codebase AI"],
  },
  {
    id: 15,
    slug: "replit",
    name: "Replit AI",
    maker: "Replit",
    website: "https://replit.com",
    tagline: "Build, deploy, and scale full-stack apps with AI",
    category: "Developer AI",
    specialty: "Full-stack app development, instant deployment, no-infrastructure dev",
    howItWorks: "Replit combines a browser-based IDE with an AI agent (powered by multiple LLMs) that can scaffold, build, debug, and deploy entire applications from plain-language descriptions. The platform handles infrastructure, scaling, and domain configuration automatically, removing the ops burden from development teams and enabling non-engineers to build functional tools.",
    captainsReview: "For aviation operators who need internal tools built fast — dispatch dashboards, maintenance tracking interfaces, crew scheduling apps — Replit dramatically lowers the build barrier. The AI agent can produce a functional prototype in hours that traditionally takes weeks. Particularly valuable for innovation teams without dedicated engineering resources who need to validate operational concepts quickly.",
    rating: 4,
    tags: ["Full-stack", "No-code", "Deployment"],
  },
  {
    id: 16,
    slug: "whisper",
    name: "Whisper",
    maker: "OpenAI",
    website: "https://openai.com/research/whisper",
    tagline: "Military-grade speech recognition for any language",
    category: "Voice AI",
    specialty: "Multilingual transcription, accent robustness, technical vocabulary",
    howItWorks: "Whisper is trained on 680,000 hours of diverse audio data including multiple languages, accents, technical domains, and noisy conditions. Its encoder-decoder transformer architecture can transcribe speech with near-human accuracy across 99 languages, handle heavy accents, and correctly recognize domain-specific terminology including aviation phraseology and ICAO alphabet usage.",
    captainsReview: "Whisper handles ATC audio, cockpit voice recorder playback, and multilingual crew communications with accuracy that commercial transcription services simply cannot match. For accident investigation teams, safety management systems, and training review — the ability to accurately transcribe technical aviation speech at scale is operationally significant. Open-source, deployable on-premise, mission-critical capable.",
    rating: 5,
    tags: ["Transcription", "Open Source", "Multilingual"],
  },
  {
    id: 17,
    slug: "otter",
    name: "Otter.ai",
    maker: "Otter.ai Inc.",
    website: "https://otter.ai",
    tagline: "AI meeting intelligence and real-time transcription",
    category: "Productivity AI",
    specialty: "Meeting transcription, action item extraction, summary generation",
    howItWorks: "Otter.ai uses speaker diarization (identifying who said what) combined with ASR transcription and NLP to produce structured meeting notes. It integrates with Zoom, Teams, and Google Meet to join calls automatically, transcribes in real-time, identifies and labels different speakers, and uses language models to extract action items and generate executive summaries.",
    captainsReview: "Operational briefings, safety committee meetings, and crew debriefs generate critical institutional knowledge that traditionally evaporates. Otter captures it all — searchable, attributed, summarized. For aviation safety management systems, having an automatic record of every safety discussion with action items linked to responsible parties is genuinely mission-changing. ROI is immediate and measurable.",
    rating: 4,
    tags: ["Meetings", "Transcription", "Productivity"],
  },
  {
    id: 18,
    slug: "notion-ai",
    name: "Notion AI",
    maker: "Notion",
    website: "https://notion.so/product/ai",
    tagline: "AI-powered knowledge management and content creation",
    category: "Productivity AI",
    specialty: "Document creation, knowledge base Q&A, workspace intelligence",
    howItWorks: "Notion AI layers GPT-4 capabilities directly into Notion's block-based document system. It can generate content, summarize pages, answer questions by searching across your entire Notion workspace, translate documents, and create structured databases from unstructured notes — all without leaving the workspace environment your team already uses.",
    captainsReview: "Aviation organizations accumulate massive institutional knowledge in SOPs, training manuals, regulatory interpretations, and historical incident data. Notion AI makes this knowledge conversationally accessible — crew members can ask questions and get cited answers from your internal documentation. The workspace Q&A capability alone transforms how organizations leverage their existing knowledge assets.",
    rating: 4,
    tags: ["Knowledge Base", "Documents", "Productivity"],
  },
  {
    id: 19,
    slug: "pika",
    name: "Pika Labs",
    maker: "Pika",
    website: "https://pika.art",
    tagline: "Fast, creative AI video generation for content teams",
    category: "Video Generation",
    specialty: "Short-form video from images or text, motion effects, animation",
    howItWorks: "Pika uses a proprietary video diffusion model optimized for short-form content (3-10 seconds), allowing users to animate still images, transform video styles, and generate clips from text prompts. The Pika 2.0 model introduced Scene ingredients — compositing real objects and characters into AI-generated environments with physical accuracy.",
    captainsReview: "For social media, internal communications, and quick training content — Pika's speed-to-output ratio is unmatched. Where Runway or Sora are precision instruments for long-form professional content, Pika is your quick-response tool for social content, animated infographics, and short explainer clips. The image-to-video capability — animating your existing photography — is particularly useful for aviation brands with strong photo assets.",
    rating: 3,
    tags: ["Video", "Social Media", "Animation"],
  },
  {
    id: 20,
    slug: "heygen",
    name: "HeyGen",
    maker: "HeyGen Inc.",
    website: "https://heygen.com",
    tagline: "AI avatar videos for training and communications at scale",
    category: "Video Generation",
    specialty: "AI avatar presenters, video translation, talking head generation",
    howItWorks: "HeyGen generates realistic AI avatar videos where a digital human — either from HeyGen's library or a custom avatar built from a video sample — speaks any script with natural mouth movements, expressions, and gesture. The platform supports 175+ languages with lip-sync translation, enabling a single piece of content to scale globally.",
    captainsReview: "For aviation training programs operating across multiple languages and geographies — HeyGen changes the economics of instructional video production. Create your chief instructor as an AI avatar once and deploy training content in 40 languages without a studio. The quality has crossed the threshold for professional corporate training. Particularly valuable for safety briefings, procedure tutorials, and onboarding content at scale.",
    rating: 4,
    tags: ["Avatars", "Training", "Translation"],
  },
  {
    id: 21,
    slug: "synthesia",
    name: "Synthesia",
    maker: "Synthesia",
    website: "https://synthesia.io",
    tagline: "Enterprise-grade AI video for professional training",
    category: "Video Generation",
    specialty: "Corporate training videos, compliance content, multilingual delivery",
    howItWorks: "Synthesia is built specifically for enterprise training and communications. Users select from 230+ AI avatars or create custom ones, write a script, and the platform generates a studio-quality video with the avatar presenting the content. Its enterprise features include team collaboration, brand kit enforcement, LMS integration, and ISO-certified data security.",
    captainsReview: "Where HeyGen excels at speed and flexibility, Synthesia wins on enterprise compliance and security. For aviation operators with strict data governance requirements — particularly defense and government aviation — the ISO 27001 certification and enterprise data controls make it the safer choice for sensitive training content. The compliance module for regulatory training content is particularly well-executed.",
    rating: 4,
    tags: ["Enterprise", "Training", "Compliance"],
  },
  {
    id: 22,
    slug: "deepgram",
    name: "Deepgram",
    maker: "Deepgram",
    website: "https://deepgram.com",
    tagline: "Real-time speech recognition built for production APIs",
    category: "Voice AI",
    specialty: "Low-latency speech-to-text API, real-time streaming, custom vocabulary",
    howItWorks: "Deepgram trains end-to-end deep learning models rather than using pipeline approaches, resulting in significantly lower latency (under 300ms for streaming) and higher accuracy on domain-specific vocabulary. Custom model training allows organizations to upload domain-specific audio and text to fine-tune models for their exact use case — critical for specialized terminology.",
    captainsReview: "For building production voice systems — ATC assistance tools, voice-commanded EFB applications, real-time cabin crew communication transcription — Deepgram's API performance is in a class above Whisper for real-time applications. The custom vocabulary training is essential for aviation: teach it METAR terminology, ICAO callsigns, and your specific phraseology. Developer-first, production-ready, aviation-capable.",
    rating: 4,
    tags: ["API", "Real-time", "Custom Models"],
  },
  {
    id: 23,
    slug: "assemblyai",
    name: "AssemblyAI",
    maker: "AssemblyAI",
    website: "https://assemblyai.com",
    tagline: "Audio intelligence beyond transcription",
    category: "Voice AI",
    specialty: "Speaker diarization, sentiment analysis, topic detection, summarization",
    howItWorks: "AssemblyAI goes beyond speech-to-text to deliver audio intelligence — combining transcription with NLP models that detect speakers, analyze sentiment, identify topics, flag content, and generate summaries all via a single API. The LeMUR feature applies LLMs directly to audio without requiring text extraction, enabling complex audio understanding queries.",
    captainsReview: "For aviation safety management, the sentiment and speaker analysis capabilities are remarkable. Processing crew debriefs to identify stress indicators, analyzing ATC recordings for communication pattern anomalies, or reviewing safety meeting audio for engagement quality — AssemblyAI turns audio archives into actionable intelligence. The LeMUR audio LLM is an emerging capability with significant safety applications.",
    rating: 4,
    tags: ["Audio Intelligence", "Safety", "API"],
  },
  {
    id: 24,
    slug: "cohere",
    name: "Cohere",
    maker: "Cohere",
    website: "https://cohere.com",
    tagline: "Enterprise NLP with on-premise deployment capability",
    category: "Enterprise AI",
    specialty: "Semantic search, document classification, private deployment",
    howItWorks: "Cohere specializes in enterprise natural language processing with a focus on search, classification, and embedding. Its Command model family is designed for business applications, and its unique deployment flexibility — Cloud, VPC, or fully on-premise — means enterprises with strict data requirements can run state-of-the-art NLP without exposing data to third-party infrastructure.",
    captainsReview: "For aviation organizations handling sensitive operational data — MRO records, incident reports, regulatory correspondence — Cohere's on-premise deployment option is a strategic differentiator. Build semantic search across your entire document library, classify incoming technical reports, or power an internal knowledge base with data that never leaves your infrastructure. The enterprise support tier is worth the investment for mission-critical deployments.",
    rating: 4,
    tags: ["Enterprise", "On-Premise", "Search"],
  },
  {
    id: 25,
    slug: "mistral",
    name: "Mistral AI",
    maker: "Mistral AI",
    website: "https://mistral.ai",
    tagline: "The best open-weight models in the world",
    category: "Language Model",
    specialty: "Open-source LLMs, efficient inference, European data sovereignty",
    howItWorks: "Mistral AI produces open-weight models using grouped query attention and sliding window attention for exceptional inference efficiency — running faster and cheaper than comparable models. Mixtral 8x22B uses a mixture-of-experts architecture activating only 2 of 8 expert networks per token, delivering GPT-4-level performance at a fraction of the compute cost.",
    captainsReview: "For European aviation organizations with GDPR requirements and data localization mandates — Mistral is strategically significant. French-headquartered with EU data residency guarantees, open weights that allow full on-premise deployment, and benchmark-competitive performance across reasoning and coding tasks. The efficiency advantage means lower inference costs for high-volume applications like real-time document processing.",
    rating: 4,
    tags: ["Open Source", "European", "Efficient"],
  },
  {
    id: 26,
    slug: "hugging-face",
    name: "Hugging Face",
    maker: "Hugging Face",
    website: "https://huggingface.co",
    tagline: "The AI platform and model hub for builders",
    category: "Developer AI",
    specialty: "Model discovery, fine-tuning, ML deployment infrastructure",
    howItWorks: "Hugging Face is the GitHub of AI — hosting 500,000+ open-source models, 150,000+ datasets, and providing the Transformers library that powers most open-source AI development. Its Inference API allows instant deployment of any hosted model, and its AutoTrain feature enables fine-tuning without writing code. The platform is the connective tissue of the open-source AI ecosystem.",
    captainsReview: "For aviation organizations building internal AI capabilities, Hugging Face is foundational infrastructure. It's where you find domain-specific models for text classification, NER for extracting entities from maintenance logs, or safety-focused fine-tuned models. If you're building custom AI applications for operational use, your team lives here. Think of it as the parts warehouse for the AI build.",
    rating: 5,
    tags: ["Models", "Open Source", "Infrastructure"],
  },
  {
    id: 27,
    slug: "descript",
    name: "Descript",
    maker: "Descript",
    website: "https://descript.com",
    tagline: "Edit audio and video by editing text",
    category: "Productivity AI",
    specialty: "Text-based audio/video editing, podcast production, screen recording",
    howItWorks: "Descript transcribes audio and video content, then lets users edit the media by editing the transcript text — deleting a sentence from the text removes the corresponding audio/video automatically. AI features include Overdub (voice cloning to fix words without re-recording), Studio Sound (background noise removal), and automatic removal of filler words across long recordings.",
    captainsReview: "For aviation training production teams creating instructional content, safety briefing videos, or podcast-style knowledge sharing — Descript dramatically accelerates the edit cycle. The text-based editing workflow is intuitive for non-editors, and the Overdub correction capability means recording errors are fixed without studio time. Particularly useful for teams producing high-volume training content where traditional video editing is a bottleneck.",
    rating: 4,
    tags: ["Audio", "Video Editing", "Podcasts"],
  },
  {
    id: 28,
    slug: "luma",
    name: "Luma Dream Machine",
    maker: "Luma AI",
    website: "https://lumalabs.ai",
    tagline: "Photorealistic video and 3D scene generation",
    category: "Video Generation",
    specialty: "3D reconstruction, photorealistic video generation, NeRF capture",
    howItWorks: "Luma AI operates across two domains: Dream Machine generates high-fidelity video from text and images using a spatially-aware model that understands 3D space; and its NeRF-based capture technology reconstructs real-world objects and environments into photorealistic 3D models from smartphone video. Both capabilities operate at commercial-grade quality.",
    captainsReview: "The 3D reconstruction capability has significant operational applications — capturing an aircraft interior, engine component, or ground facility with a smartphone and generating a navigable 3D model for training or documentation purposes. For MRO teams documenting complex repair procedures or training departments creating immersive facility orientations, this represents a step-change in documentation capability.",
    rating: 4,
    tags: ["3D", "Video", "Spatial AI"],
  },
  {
    id: 29,
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    maker: "Adobe",
    website: "https://firefly.adobe.com",
    tagline: "Commercially safe generative AI inside creative workflows",
    category: "Image Generation",
    specialty: "Commercial-safe image generation, Creative Cloud integration, brand control",
    howItWorks: "Adobe Firefly is trained exclusively on Adobe Stock images, openly licensed content, and public domain material — making all outputs commercially safe with full indemnification from Adobe. It integrates directly into Photoshop, Illustrator, and Express through generative fill, text effects, and vector generation, working within existing creative workflows rather than replacing them.",
    captainsReview: "For aviation marketing teams producing commercial assets — advertising materials, brand campaigns, fleet photography — the commercial safety guarantee and Adobe integration are operationally critical. No IP concerns on outputs, no workflow disruption, and the generative fill capability transforms photo retouching (replacing backgrounds, removing ground equipment, creating compositional variations) from hours to minutes.",
    rating: 4,
    tags: ["Commercial Safe", "Adobe", "Marketing"],
  },
  {
    id: 30,
    slug: "palantir",
    name: "Palantir AIP",
    maker: "Palantir Technologies",
    website: "https://palantir.com/platforms/aip",
    tagline: "Operational AI for defense-grade intelligence requirements",
    category: "Enterprise AI",
    specialty: "Defense AI, large-scale data integration, operational decision intelligence",
    howItWorks: "Palantir's Artificial Intelligence Platform (AIP) sits on top of Palantir Foundry — their data integration and analysis platform used by military and intelligence agencies. AIP brings LLMs into operational contexts with strict access controls, allowing analysts and operators to query vast multi-source datasets using natural language while maintaining classification-level security and full audit trails.",
    captainsReview: "Palantir AIP is not for civilian aviation operators — it is purpose-built for the intersection of aviation and national security. Defense contractors, government aviation agencies, and military aviation commands represent the target environment. The capability for classified data integration, mission-level AI assistance, and cross-source intelligence analysis is unmatched. If your operations require security clearances, this is the platform. Cleared for all classification levels.",
    rating: 5,
    tags: ["Defense", "Government", "Intelligence"],
  },
];

export const CATEGORIES = [...new Set(AI_TOOLS.map((t) => t.category))];

export function getToolBySlug(slug: string): AiTool | undefined {
  return AI_TOOLS.find((t) => t.slug === slug);
}
